### ISSUE TITLE
week9 作業提問(2)

### ISSUE THREAD

**Issue by tzminch** [PeterWolf-tw/NTNU_TextProcessing_2020#18]
老師好，這週作業中有需要把 "news.json" 中 "content" 中的涉案金額截取出來。
想請問Articut套件中有這樣的功能嗎？目前我找到的文件只有這個https://github.com/Droidtown/ArticutAPI/blob/master/Docs/KNOWLEDGE_currency.md

再請老師幫忙解惑，感謝！

**Comment by PeterWolf-tw** [comment]
有的。範例可以找：
https://github.com/Droidtown/ArticutAPI/blob/master/ArticutAPI.ipynb
這段 「#列出所有的貨幣金額」

**Comment by tzminch** [comment]
了解，謝謝老師。
